<?php 

/*
  HTML for widgets are generated by Wordpress
  You have 3 options for how to fix the styling for default widgets
  1. Override HTML generated by WP - BAD - Don't hack the WP core
  2. Create own version of the widget - GOOD - have complete control of entire widget
  3. Hack the CSS file - EASY - least amount of work

  For option 3, see what classes WP generates for the widget and modify
  the styles for the theme.
*/

function ho_widgets () {
  register_sidebar([
    'name'            => __( 'My First Theme Sidebar', 'htmlonly' ),
    'id'              => 'ho_sidebar',
    'description'     => __( 'Sidebar for the HTML Only theme' ),
    // The id and class below are placeholders...see documentation
    'before_widget'   => '<div id="%1$s" class="widget %2$s">',
    'after_widget'    => '</div>',
    'before_title'    => '<h4>',
    'after_title'     => '</h4>'
  ]);
}